Страница входа и регистрации
UralGuru/FoodCourt pull request #1
Opened 2022-12-10 10:44 UTC by UralGuru

Сверстал страницы входа и регистрации.
Реализовал переход из страницы входа на страницу регистрации и обратно. 
Прописана логика логинизации.
Подключил управление состоянием - ReduxToolkit.
Связался с бекендом - Axios.

2022-12-10 12:40 UTC, Vikitoki requested changes

2022-12-10 12:40 UTC, Vikitoki commented on .eslintignore
> -.next/
зачем ты удалил .eslintignore и .eslintrc.json???

2022-12-10 12:40 UTC, Vikitoki commented on constants/types.ts
> +export interface LoginType {
опять Type в названии. Везде убрать!

2022-12-10 12:40 UTC, Vikitoki commented on constants/types.ts
> +  accessToken: string | null;
я уже говорил, что писать string | null максимально плохая идея. Вместо null используй пустую строку

2022-12-10 12:40 UTC, Vikitoki commented on package.json
> -    "prepare-for-pull": "npm-run-all --parallel lint style-format code-format"
какой смысл ты убрал форматирование стилей?

2022-12-10 12:40 UTC, Vikitoki commented on package.json
> -    "prepare-for-pull": "npm-run-all --parallel lint style-format code-format"
какой смысл ты убрал форматирование стилей?

2022-12-10 12:40 UTC, Vikitoki commented on package.json
> +    "classnames": "2.3.1",
classnames должна лежать в dependencies

2022-12-10 12:40 UTC, Vikitoki commented on pages-content/home/index.tsx
> +  const user = useSelector((state: any) => state.auth);
не any! Кто-то невнимательно читает документацию?

2022-12-10 12:40 UTC, Vikitoki commented on pages-content/home/index.tsx
> +    dispatch(clearMessage());
логика этих двух событий должна быть разделена на 2 useEffect

2022-12-10 12:40 UTC, Vikitoki commented on pages/404.tsx
> +    setTimeout(() => {
Вот будет интересно, когда твой компонент исчезнет до того, как пройдут 3 секунды

2022-12-10 12:40 UTC, Vikitoki commented on pages/404.tsx
> +      style={{
максимально стараемся избегать inline стилей

2022-12-10 12:40 UTC, Vikitoki commented on pages/auth/auth.module.scss
> +  margin-top: 1em;
где-то em, где-то px. Зачем такой микс? Делай всё в px

2022-12-10 12:40 UTC, Vikitoki commented on pages/auth/auth.module.scss
> +  width: 90vw;
нет, width: 100%

2022-12-10 12:40 UTC, Vikitoki commented on pages/auth/auth.module.scss
> +  border-bottom: 1px solid #494949;
#494949 - в переменную цвета, также как и в свойстве background

2022-12-10 12:40 UTC, Vikitoki commented on pages/auth/auth.module.scss
> +  width: 90vw;
не знаю кто тебя этому научил, но vw старайся не использовать

2022-12-10 12:40 UTC, Vikitoki commented on pages/auth/auth.module.scss
> +  -webkit-tap-highlight-color: transparent;
префиксы убирай, они будут добавлены автоматически

2022-12-10 12:40 UTC, Vikitoki commented on pages/auth/auth.module.scss
> +.a {
и что это за название класса? Кто так пишет?

2022-12-10 12:40 UTC, Vikitoki commented on pages/auth/auth.module.scss
> +  user-select: none;
опять какие-то избыточные свойства по дефолту выставляешь

2022-12-10 12:40 UTC, Vikitoki commented on pages/auth/login.tsx
> +import React, { useState, useEffect } from 'react';
Этот файл покажу тебе как улучшить. Остальные, сделаешь по подобию

2022-12-10 12:40 UTC, Vikitoki commented on pages/auth/register.tsx
> +              // onClick={() => AuthService.loginWidthGoogle()}
и что это?

2022-12-10 12:40 UTC, Vikitoki commented on services/auth.service.ts
> +import axios from 'axios';
вообще не так

2022-12-10 12:40 UTC, Vikitoki commented on shared/urls.ts
> +export const UrlManager: any = {
зачем ты ставишь any? Кто тебя тут просит что-то типизировать?

UrlManager должен быть не объектом, а классом-синглтоном

2022-12-10 12:40 UTC, Vikitoki commented on store/hook.ts
> +import { useDispatch, useSelector, TypedUseSelectorHook } from 'react-redux';
название файла не hook, а hooks, и они должны лежать не здесь, а в shared

2022-12-10 12:40 UTC, Vikitoki commented on store/slices/authSlice.ts
> +import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
всё также У-ЖАС-НО. Ты точно читал про redux-toolkit??

2022-12-10 12:40 UTC, Vikitoki commented on styles/theme.scss
> +$fw-open-sans-light: 300;
опять же, мы уже говорили, что не надо font-weight свойство загонять в переменные - это перебор

2022-12-10 12:40 UTC, Vikitoki commented on styles/theme.scss
> +//шрифты
название файла дурацкое. Всё что ты пишешь комментариями, должно лежать в отдельных файлах

2022-12-10 12:40 UTC, Vikitoki commented on tsconfig.json
> -      "@styles/*": [
видишь здесь хоть какие-то изменения? Вот, и я их не вижу! А так происходит, потому что ты не указал своей IDE на настройки локального prettier

2022-12-11 17:47 UTC, DanilKlus commented on pages-content/home/index.tsx
> +  return (
привет

2023-01-30 11:51 UTC, merged